name: build
on: [ push, pull_request ]
jobs:

  Linux:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libunwind-dev libdw-dev libzstd-dev zstd
        python -m pip install --upgrade pip setuptools wheel build

    - name: Build components
      run: |
          mkdir build
          cd    build
          cmake .. -DSSLOG_BUILD_PYTHON_READER=ON
          make -j $(nproc)

    - name: Install python packages
      run: |
          cd   build
          make install

    - name: Run tests
      run: |
          cd test
          ./run_tests.py . -v -ns "*performance*"

  Windows:
    runs-on: windows-2019
    env:
      VS_PATH: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\
    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download Zstandard release package 1.5.7
      run: |
          mkdir zstd_dev
          cd zstd_dev
          Invoke-WebRequest -Uri "https://github.com/facebook/zstd/releases/download/v1.5.7/zstd-v1.5.7-win64.zip" -OutFile "zstd-v1.5.7-win64.zip"
          Expand-Archive -Path "zstd-v1.5.7-win64.zip" -DestinationPath "."
          Rename-Item -Path "zstd-v1.5.7-win64" -NewName zstd

    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      shell: cmd
      run: |
          python -m pip install --upgrade pip setuptools wheel build

    - name: Build components
      shell: cmd
      run: |
          mkdir build
          cd build
          call "%VS_PATH%\VC\Auxiliary\Build\vcvars64.bat"
          set INCLUDE=%GITHUB_WORKSPACE%\zstd_dev\zstd\include;%INCLUDE%
          set LIB=%GITHUB_WORKSPACE%\zstd_dev\zstd\dll;%LIB%
          set zstd_LIBRARY=%GITHUB_WORKSPACE%\zstd_dev\zstd\dll\libzstd.dll
          cmake .. -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release -DSSLOG_BUILD_PYTHON_READER=ON -Dzstd_INCLUDE_DIR="%GITHUB_WORKSPACE%\zstd_dev\zstd\include" -Dzstd_LIBRARY="%GITHUB_WORKSPACE%\zstd_dev\zstd\dll\libzstd.dll.a"
          nmake

    - name: Install python packages
      shell: cmd
      run: |
          cd build
          call "%VS_PATH%\VC\Auxiliary\Build\vcvars64.bat"
          nmake install

    - name: Run tests
      shell: cmd
      run: |
          cd test
          call "%VS_PATH%\VC\Auxiliary\Build\vcvars64.bat"
          python run_tests.py . -v -ns "*performance*"


  Wheels:
    runs-on: windows-2019
    env:
      VS_PATH: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\
    steps:

    - uses: actions/checkout@v4

    - name: Download Zstandard release package 1.5.7
      run: |
          mkdir zstd_dev
          cd zstd_dev
          Invoke-WebRequest -Uri "https://github.com/facebook/zstd/releases/download/v1.5.7/zstd-v1.5.7-win64.zip" -OutFile "zstd-v1.5.7-win64.zip"
          Expand-Archive -Path "zstd-v1.5.7-win64.zip" -DestinationPath "."
          Rename-Item -Path "zstd-v1.5.7-win64" -NewName zstd

    - uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    - name: Install dependencies
      shell: cmd
      run: |
          python -m pip install --upgrade pip setuptools wheel build
          mkdir build38
    - name: Create a wheel package instrumentation module for python 3.8
      shell: cmd
      run: |
          cd build38
          call "%VS_PATH%\VC\Auxiliary\Build\vcvars64.bat"
          set INCLUDE=%GITHUB_WORKSPACE%\zstd_dev\zstd\include;%INCLUDE%
          set LIB=%GITHUB_WORKSPACE%\zstd_dev\zstd\dll;%LIB%
          set zstd_LIBRARY=%GITHUB_WORKSPACE%\zstd_dev\zstd\dll\libzstd.dll
          cmake .. -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release -DSSLOG_BUILD_PYTHON_READER=ON -Dzstd_INCLUDE_DIR="%GITHUB_WORKSPACE%\zstd_dev\zstd\include" -Dzstd_LIBRARY="%GITHUB_WORKSPACE%\zstd_dev\zstd\dll\libzstd.dll"
          nmake python_reader

    - uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - name: Install dependencies
      shell: cmd
      run: |
          python -m pip install --upgrade pip setuptools wheel build
          mkdir build39
    - name: Create a wheel package instrumentation module for python 3.9
      shell: cmd
      run: |
          cd build39
          call "%VS_PATH%\VC\Auxiliary\Build\vcvars64.bat"
          set INCLUDE=%GITHUB_WORKSPACE%\zstd_dev\zstd\include;%INCLUDE%
          set LIB=%GITHUB_WORKSPACE%\zstd_dev\zstd\dll;%LIB%
          set zstd_LIBRARY=%GITHUB_WORKSPACE%\zstd_dev\zstd\dll\libzstd.dll
          cmake .. -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release -DSSLOG_BUILD_PYTHON_READER=ON -Dzstd_INCLUDE_DIR="%GITHUB_WORKSPACE%\zstd_dev\zstd\include" -Dzstd_LIBRARY="%GITHUB_WORKSPACE%\zstd_dev\zstd\dll\libzstd.dll"
          nmake python_reader

    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      shell: cmd
      run: |
          python -m pip install --upgrade pip setuptools wheel build
          mkdir build310
    - name: Create a wheel package instrumentation module for python 3.10
      shell: cmd
      run: |
          cd build310
          call "%VS_PATH%\VC\Auxiliary\Build\vcvars64.bat"
          set INCLUDE=%GITHUB_WORKSPACE%\zstd_dev\zstd\include;%INCLUDE%
          set LIB=%GITHUB_WORKSPACE%\zstd_dev\zstd\dll;%LIB%
          set zstd_LIBRARY=%GITHUB_WORKSPACE%\zstd_dev\zstd\dll\libzstd.dll
          cmake .. -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release -DSSLOG_BUILD_PYTHON_READER=ON -Dzstd_INCLUDE_DIR="%GITHUB_WORKSPACE%\zstd_dev\zstd\include" -Dzstd_LIBRARY="%GITHUB_WORKSPACE%\zstd_dev\zstd\dll\libzstd.dll"
          nmake python_reader

    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      shell: cmd
      run: |
          python -m pip install --upgrade pip setuptools wheel build
          mkdir build311
    - name: Create a source and wheel package instrumentation module for python 3.11
      shell: cmd
      run: |
          cd build311
          call "%VS_PATH%\VC\Auxiliary\Build\vcvars64.bat"
          set INCLUDE=%GITHUB_WORKSPACE%\zstd_dev\zstd\include;%INCLUDE%
          set LIB=%GITHUB_WORKSPACE%\zstd_dev\zstd\dll;%LIB%
          set zstd_LIBRARY=%GITHUB_WORKSPACE%\zstd_dev\zstd\dll\libzstd.dll
          cmake .. -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release -DSSLOG_BUILD_PYTHON_READER=ON -Dzstd_INCLUDE_DIR="%GITHUB_WORKSPACE%\zstd_dev\zstd\include" -Dzstd_LIBRARY="%GITHUB_WORKSPACE%\zstd_dev\zstd\dll\libzstd.dll"
          nmake python_reader

    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      shell: cmd
      run: |
          python -m pip install --upgrade pip setuptools wheel build
          mkdir build312
    - name: Create a source and wheel package instrumentation module for python 3.12
      shell: cmd
      run: |
          cd build312
          call "%VS_PATH%\VC\Auxiliary\Build\vcvars64.bat"
          set INCLUDE=%GITHUB_WORKSPACE%\zstd_dev\zstd\include;%INCLUDE%
          set LIB=%GITHUB_WORKSPACE%\zstd_dev\zstd\dll;%LIB%
          set zstd_LIBRARY=%GITHUB_WORKSPACE%\zstd_dev\zstd\dll\libzstd.dll
          cmake .. -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release -DSSLOG_BUILD_PYTHON_READER=ON -Dzstd_INCLUDE_DIR="%GITHUB_WORKSPACE%\zstd_dev\zstd\include" -Dzstd_LIBRARY="%GITHUB_WORKSPACE%\zstd_dev\zstd\dll\libzstd.dll"
          nmake python_reader

    - uses: actions/upload-artifact@v4
      with:
        name: Python 3.8 sslogread wheel
        path: build38/python/dist/*

    - uses: actions/upload-artifact@v4
      with:
        name: Python 3.9 sslogread wheel
        path: build39/python/dist/*

    - uses: actions/upload-artifact@v4
      with:
        name: Python 3.10 sslogread wheel
        path: build310/python/dist/*

    - uses: actions/upload-artifact@v4
      with:
        name: Python 3.11 sslogread wheel
        path: build311/python/dist/*

    - uses: actions/upload-artifact@v4
      with:
        name: Python 3.12 sslogread wheel
        path: build312/python/dist/*

    - uses: actions/upload-artifact@v4
      with:
        name: Python sslogread source
        path: build312/python/dist/*.gz
